### ISSUE TITLE
BUG: Parsing of time can have unexpected results

### ISSUE THREAD

**Issue by Nattaro13** [cs2103jan2016-f14-4j/main#112]
### <s>Grammatically incorrect dates:
---
<li> <b> add project meeting at 3pm by 17 Feb 2016 </b> returns today's date, 3pm </s> 
### <s>Splits wrongly and puts into wrong category
---
<li><b> add project meeting on cells from 4pm to 5pm </b> goes to deadline instead of event </s>
### <s> PrettyTime cannot parse the following format:
---
<li> <b> add project meeting on 19 feb from 4pm to 5pm </b> causes the parser to return error because PrettyTime parses it as 19 feb [current time], and ignores the 4pm to 5pm.
<li> however, PrettyTime accepts <b>add project meeting from 4pm to 5pm on 19 feb</b> </s>
### <s>PrettyTime parses wrongly when there are numbers in a task name</s> solved
---
<s><li> <b>add meeting2 on 15 Mar 3pm </b> returns me a meeting on 15 Mar at 2am. 
<li><b>add meeting3 at 3pm on 15Mar</b> returns me 13 march at 3am. </s>

**Comment by Nattaro13** [comment]
#63

**Comment by Nattaro13** [comment]
@cs2103jan2016-f14-4j/team-bit any other bugs related to parsing time can be posted here

**Comment by Nattaro13** [comment]
### Implement Pattern Matcher in Parser to handle these erroneous cases

**Comment by Nattaro13** [comment]
Todo: 
- Implement PatternMatcher into ParseAdd
- Redo the main method of ParseAdd to get each individual component of a user's input first, rather than parsing the whole thing into a function straightaway, as it might parse a place as a time

**Comment by dq-dx** [comment]
Bug: Cannot combine "tmr" with a time even though "tomorrow" works.

E.g. Doing this:
`add foobar by tmr 11pm`
`add foobar by tmr at 11pm`
will both add a deadline for 11pm _today_.

But funnily enough, replacing "tmr" with "tomorrow" works.

**Comment by Nattaro13** [comment]
Above bugs have been fixed.
### Keeping this thread open for future date/time parsing bugs

**Comment by dq-dx** [comment]
I think there's no support for adding events with the start date as today.
E.g. these do not work:
```
add event from **today** to tmr
add event from **today** to 22 mar
```
But I _can _, in fact, have tmr as the start date:
add event from **tmr **to 23 mar
add event from **tmr **to this wed

**Comment by Nattaro13** [comment]
@dq-dx did you try that on your branch or mine? because "add event from today to tmr" works perfectly fine on my branch. no issues whatsoever.

**Comment by dq-dx** [comment]
@Nattaro13 Actually, I was trying that on Logic branch because for some reason I couldn't run UIMain on the mater/parser/ui branch.

Nvm, works now.

**Comment by Nattaro13** [comment]
Unable to detect dates for the following: 
- add meet friend to do pde at 12pm tomorrow 
- add meet friend to do pde tomorrow 
- add go home on this friday night

**Comment by dq-dx** [comment]
These don't seem to work (on master branch):
```
add sdasda by mon
add asdsad on sat
add sdasad by sat
```

**Comment by Nattaro13** [comment]
solved #224 , linked to this as well

**Comment by dq-dx** [comment]
On parser and master branch: 

- When I try to add a deadline and specify numbers only (no am/pm/h), the program stops responding.
E.g.
`
add dasdas by 1337
add dasdsa by 1
add dasdsa on 0
add asddsa at 42
`

- Not sure if this is considered a bug or is even worth fixing, but if I add a task with "tmr" in its name, all the instances of "tmr" will be replaced by "tomorrow" in the task name after it is added.
E.g.
`
add tmr lunch by tmr    => Name: Tomorrow lunch
add lunch tmr by tmr    => Name: Lunch tomorrow
add tmr tmr by tmr       => Name: Tomorrow tomorrow
`

- Also not sure if this is a bug or just a limitation, but `add event from 12pm to tmr` doesn't work. It gives starting > ending time, even though `set 1 [12pm, tmr]` works as expected.

**Comment by Nattaro13** [comment]
2 minor problems with date/time parsing left uncorrected. Will not be fixing them anymore.
