### ISSUE TITLE
Logic: Perform necessary operations when Storage throws Exceptions

### ISSUE THREAD

**Issue by Lvl100p** [cs2103jan2016-f14-4j/main#234]

**Comment by dq-dx** [comment]
Fixed setdir + undo in #252.
Will do more detailed LogicException messages for user feedback.

**Comment by dq-dx** [comment]
Done in 34db669a548931f433aaf81f1a3730eca41c03fd: Edits to Storage & LogicMemory to display various kinds of exception messages to the user for the setdir command.
