### ISSUE TITLE
Add methods in Logic.java once Storage API is up

### ISSUE THREAD

**Issue by Lvl100p** [cs2103jan2016-f14-4j/main#33]

**Comment by dq-dx** [comment]
I think Logic can keep all the tasks in a data structure in memory for easier manipulation (i.e. CRUD) -- maybe as a sub-component called Data or Memory?

After C/R/D, Logic then calls Storage to write to file. In this way, Logic will be less dependent on Storage.

**Comment by Nattaro13** [comment]
I think Storage should have a copy of the Task list in memory/ or Storage can have the task list, and Logic can always getTaskList() / or get each individual arrayLists for floating/deadline/event task 
eg. on program start up, logic calls Storage to get the Tasklist anyway, so might as well store TaskList in Storage?

**Comment by Lvl100p** [comment]
I think it's more appropriate for Storage to have the various Task lists, since it's the component that has direct access to the files. If any sorting needs to be done, Storage can pass the relevant Task lists to Logic which will then sort the lists and return them to Storage.

**Comment by Nattaro13** [comment]
sounds good. 
as for sorting, i think it kind of uses up alot of resources to push a list of n elements back and forth (runtime O(n)) 
how about Storage having a method, for example, called sortFloating(), then Logic just calls storage.sortFloating() ? 
since Task has already implemented comparable, its easy for Dylan to call Collections.sort(arraylist)

**Comment by dq-dx** [comment]
Oh I didn't think about making separate ArrayLists, and corresponding data files, for each type of task. The way Storage is currently implemented, Logic has to manually set the filename before saving if you want to have separate data files for floating/deadline/event tasks.
